import avatar from './avatar.png';
import loginIllustration from './login-illustration.png';
import userImage from './user-image.png';

export { default as Logo } from './icons/Logo';
export { default as Notification } from './icons/Notification';
export { default as Search } from './icons/Search';
export { default as DropDown } from './icons/DropDown';
export { default as BriefCase } from './icons/BriefCase';
export { default as OrgDropDown } from './icons/OrgDropDown';
export { default as Home } from './icons/Home';
export { default as Users } from './icons/Users';
export { default as Guarantors } from './icons/Guarantors';
export { default as Sack } from './icons/Sack';
export { default as Handshake } from './icons/Handshake';
export { default as Savings } from './icons/Savings';
export { default as LoanRequests } from './icons/LoanRequests';
export { default as WhiteList } from './icons/WhiteList';
export { default as Karma } from './icons/Karma';
export { default as FeesAndCharges } from './icons/FeesAndCharges';
export { default as Reports } from './icons/Reports';
export { default as SavingsProducts } from './icons/SavingsProducts';
export { default as ServiceAccount } from './icons/ServiceAccount';
export { default as Services } from './icons/Services';
export { default as Settlements } from './icons/Settlements';
export { default as Transactions } from './icons/Transactions';
export { default as Preferences } from './icons/Preferences';
export { default as FeesAndPricing } from './icons/FeesAndPricing';
export { default as AuditLogs } from './icons/AuditLogs';
export { default as DashboardUsers } from './icons/DashboardUsers';
export { default as DashboardActiveUsers } from './icons/DashboardActiveUsers';
export { default as DashboardUsersWithLoans } from './icons/DashboardUsersWithLoans';
export { default as DashboardUsersWithSavings } from './icons/DashboardUsersWithSavings';
export { default as Filter } from './icons/Filter';
export { default as SideMenu } from './icons/SideMenu';
export { default as View } from './icons/View';
export { default as Activate } from './icons/Activate';
export { default as Blacklist } from './icons/Blacklist';
export { default as LeftNavigation } from './icons/LeftNavigation';
export { default as RightNavigation } from './icons/RightNavigation';
export { default as Loading } from './icons/Loading';
export { default as DateIcon } from './icons/DateIcon';
export { default as LeftArrow } from './icons/LeftArrow';
export { default as Star } from './icons/Star';
export { default as UnStar } from './icons/UnStar';
export { default as LogOut } from './icons/LogOut';
export { default as Notfound } from './icons/NotFound';
export { loginIllustration, userImage, avatar };
